In [5]:
from sklearn.linear_model import Perceptron
from sklearn.metrics import classification_report
import numpy as np

# Define the input and output for the logic functions
X_and = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_and = [0, 0, 0, 1]

X_or = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_or = [0, 1, 1, 1]

X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_xor = [0, 1, 1, 0]

# Create a Perceptron classifier
clf = Perceptron(max_iter=1000, tol=1e-3)

print("````````````````````````````````````````````````````````````")

# Train the classifier on the AND function
clf.fit(X_and, y_and)

# Test the classifier on some input values and calculate performance metrics
y_pred_and = clf.predict(X_and)

print("AND")
print("Weights after training:")
print(clf.coef_)

print("Score:")
print(clf.score(X_and, y_and))

# Print the performance metrics for the AND function
report_and = classification_report(y_and, y_pred_and, zero_division=1)
print(report_and)

print("````````````````````````````````````````````````````````````")

# Train the classifier on the OR function
clf.fit(X_or, y_or)

# Test the classifier on some input values and calculate performance metrics
y_pred_or = clf.predict(X_or)

print("OR")
print("Weights after training:")
print(clf.coef_)

print("Score:")
print(clf.score(X_or, y_or))

# Print the performance metrics for the OR function
report_or = classification_report(y_or, y_pred_or, zero_division=1)
print(report_or)

print("````````````````````````````````````````````````````````````")
# Train the classifier on the XOR function
clf.fit(X_xor, y_xor)

# Test the classifier on some input values and calculate performance metrics
y_pred_xor = clf.predict(X_xor)

print("XOR")
print("Weights after training:")
print(clf.coef_)

print("Score:")
print(clf.score(X_xor, y_xor))

# Print the performance metrics for the XOR function
report_xor = classification_report(y_xor, y_pred_xor, zero_division=1)
print(report_xor)


````````````````````````````````````````````````````````````
AND
Weights after training:
[[2. 2.]]
Score:
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         1

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4

````````````````````````````````````````````````````````````
OR
Weights after training:
[[2. 2.]]
Score:
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         3

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4

````````````````````````````````````````````````````````````
XOR
Weights after training:
[[0. 0.]]
Score:
0.5
              pre