Train the network for implementing single layer perceptron classifier for the following logic functions: OR, AND

In [1]:
import numpy as np

In [2]:
class NeuralNetwork():
    def __init__(self):
        np.random.seed(1)
        self.weight_matrix = 2 * np.random.random((2, 1)) - 1
        
    def derivative(self, x):
        return 1 - np.tanh(x)**2
    
    def fp(self, input_layer):
        return np.tanh(np.dot(input_layer, self.weight_matrix))
    
    def train(self, input_layer, output_layer, epochs):
        
        for i in range(epochs):
            output = self.fp(input_layer)
            
#             Backward Propogation
            error = output_layer - output
            adj = np.dot(input_layer.T, error * self.derivative(output))
            self.weight_matrix += adj

In [3]:
nn = NeuralNetwork()
print("Current weight matrix: (Before training): \n", nn.weight_matrix)

Current weight matrix: (Before training): 
 [[-0.16595599]
 [ 0.44064899]]


In [4]:
input_layer = np.array([[0, 0], [0, 1], [0, 1], [1, 1]])
output_layer = np.array([[1], [1], [1], [0]])

In [5]:
nn.train(input_layer, output_layer, 10000)
print("Weight matrix after training: \n", nn.weight_matrix)

Weight matrix after training: 
 [[-4.86888697]
 [ 4.86144087]]


In [6]:
print("Predicting output for [1, 0]: ", round(nn.fp(np.array([1, 0]))[0]))

Predicting output for [1, 0]:  -1


<h2><em>Accuracy & Error Rate: </em></h2>

In [7]:
correct = 0
for act, inp in zip(output_layer, input_layer):
    if act == round(nn.fp(inp)[0]):
        correct+=1
        
print("Accuracy: ", correct/output_layer.shape[0] * 100)
print("Error rate: ", (1 - correct/output_layer.shape[0]) * 100)

Accuracy:  75.0
Error rate:  25.0


<h3>Training for: AND gate </h3>

In [8]:
nn = NeuralNetwork()
print("Current weight matrix: (Before training): \n", nn.weight_matrix)
input_layer = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
output_layer = np.array([[0], [0], [0], [1]])
nn.train(input_layer, output_layer, 10000)
print("Weight matrix after training: \n", nn.weight_matrix)
print("Predicting output for [1, 0]: ", round(nn.fp(np.array([1, 0]))[0]))

Current weight matrix: (Before training): 
 [[-0.16595599]
 [ 0.44064899]]
Weight matrix after training: 
 [[0.33928515]
 [0.33928515]]
Predicting output for [1, 0]:  0


In [9]:
correct = 0
for act, inp in zip(output_layer, input_layer):
    if act == round(nn.fp(inp)[0]):
        correct+=1
        
print("Accuracy: ", correct/output_layer.shape[0] * 100)
print("Error rate: ", (1 - correct/output_layer.shape[0]) * 100)

Accuracy:  100.0
Error rate:  0.0


<h3>Training for: OR gate </h3>

In [10]:
nn = NeuralNetwork()
print("Current weight matrix: (Before training): \n", nn.weight_matrix)
input_layer = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
output_layer = np.array([[0], [1], [1], [1]])
nn.train(input_layer, output_layer, 10000)
print("Weight matrix after training: \n", nn.weight_matrix)
print("Predicting output for [1, 0]: ", round(nn.fp(np.array([1, 0]))[0]))

Current weight matrix: (Before training): 
 [[-0.16595599]
 [ 0.44064899]]
Weight matrix after training: 
 [[4.86602761]
 [4.86598247]]
Predicting output for [1, 0]:  1


In [11]:
correct = 0
for act, inp in zip(output_layer, input_layer):
    if act == round(nn.fp(inp)[0]):
        correct+=1
        
print("Accuracy: ", correct/output_layer.shape[0] * 100)
print("Error rate: ", (1 - correct/output_layer.shape[0]) * 100)

Accuracy:  100.0
Error rate:  0.0


<h3>Training for: XOR gate </h3>

In [12]:
nn = NeuralNetwork()
print("Current weight matrix: (Before training): \n", nn.weight_matrix)
input_layer = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
output_layer = np.array([[0], [1], [1], [0]])
nn.train(input_layer, output_layer, 10000)
print("Weight matrix after training: \n", nn.weight_matrix)
print("Predicting output for [1, 0]: ", round(nn.fp(np.array([1, 0]))[0]))

Current weight matrix: (Before training): 
 [[-0.16595599]
 [ 0.44064899]]
Weight matrix after training: 
 [[0.4895021]
 [0.4895021]]
Predicting output for [1, 0]:  0


In [13]:
correct = 0
for act, inp in zip(output_layer, input_layer):
    if act == round(nn.fp(inp)[0]):
        correct+=1
        
print("Accuracy: ", correct/output_layer.shape[0] * 100)
print("Error rate: ", (1 - correct/output_layer.shape[0]) * 100)

Accuracy:  25.0
Error rate:  75.0
